# Account Session

# ### Account Info After Login
# GET http://localhost:3000/api/users/info
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyaWNvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlhdCI6MTY2NzMwNTE0OX0.KYpp05shsojREKjgcNlP_F6vxMYFl1cmhForm-201TI

# ### Get All Account
# GET http://localhost:3000/api/users

### Add Account
# POST http://localhost:3000/api/users
# Content-Type: application/json

# {
#     "email": "ri@gmail.com",
#     "password": "12"
# }

### Update Account
# PUT http://localhost:3000/api/users
# Content-Type: application/json

# {
#     "id": "3",
#     "email": "inihasiledit@gmail.com",
#     "password": "123"
# }

# ### Delete Account
# DELETE http://localhost:3000/api/users/3





# # ToDo Session

# ## Get Todo Based on LogIn Account
# GET http://localhost:3000/api/todo
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyaWNvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlhdCI6MTY2NzMwNTMzMH0._wLPwU7zkL6n6cNe_qvfMG8l9lIW6ZKq69cjQqU6f2Y

### Add ToDo to Login Account
# POST http://localhost:3000/api/todo
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyaWNvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlhdCI6MTY2NzMwNTMzMH0._wLPwU7zkL6n6cNe_qvfMG8l9lIW6ZKq69cjQqU6f2Y
# Content-Type: application/json

# {
#     "todo": "ini barusan aku add"
# }

# ### Update ToDo
# PUT http://localhost:3000/api/todo
# Content-Type: application/json

# {
#     "id": 4,
#     "todo": "ini yang tak delete"
# }

# ### Delete ToDo
# DELETE http://localhost:3000/api/todo/4


# ### LogIn Account
# POST http://localhost:3000/api/login
# Content-Type: application/json

# {
#     "email": "rico@gmail.com",
#     "password": "1234"
# }

